'use strict';
globalThis.POURMIND_LEARNING = {
  topics: [
    {id:'technique', title:'Mixing techniques', description:'Stir, shake, strain and build with confidence.'},
    {id:'ingredients', title:'Know your ingredients', description:'Understand citrus, sweeteners, vermouth and liqueurs.'},
    {id:'families', title:'Cocktail families', description:'Recognize the patterns behind familiar recipes.'},
    {id:'serving', title:'Glassware & finishing', description:'Choose the glass, ice and garnish for the drink.'},
    {id:'balance', title:'Balance & good habits', description:'Measure well, taste thoughtfully and keep ingredients fresh.'}
  ],
  questions: [
    {id:'stir-old-fashioned', topic:'technique', question:'How do you mix a classic Old Fashioned?', options:['Shake it with ice','Stir it with ice','Blend it with crushed ice'], correct:1, explanation:'Stirring chills and dilutes a spirit-forward drink while keeping it clear and silky.'},
    {id:'shake-daiquiri', topic:'technique', question:'Why do you shake a classic Daiquiri?', options:['To combine rum, lime, and syrup','To keep the ingredients separate','To warm the rum'], correct:0, explanation:'Shaking combines citrus and syrup with the spirit while chilling, diluting and lightly aerating the drink.'},
    {id:'express-orange', topic:'serving', question:'How do you add an orange peel to an Old Fashioned?', options:['Blend it into the drink','Express its oils over the surface','Leave it in the mixing tin'], correct:1, explanation:'Gently squeezing the peel releases aromatic oils over the drink. Place the peel in the glass to finish.'},
    {id:'soda-last', topic:'technique', question:'When should you add soda water to a Tom Collins?', options:['Before shaking everything together','After shaking and straining the other ingredients','Before squeezing the lemon'], correct:1, explanation:'Add carbonation last and stir gently. Shaking soda releases its bubbles and can force open a shaker.'},
    {id:'dry-shake', topic:'technique', question:'What does a dry shake mean?', options:['Shaking ingredients without ice','Shaking an empty shaker','Shaking with extra-large ice cubes'], correct:0, explanation:'A dry shake uses no ice. It helps build foam in egg-white sours; follow it with an ice shake to chill the drink.'},
    {id:'fine-strain', topic:'technique', question:'Why fine-strain a Southside through a small mesh strainer?', options:['To add more sweetness','To warm the cocktail','To remove small mint fragments and ice shards'], correct:2, explanation:'A fine strainer catches mint fragments and small ice shards that pass through the main cocktail strainer.'},
    {id:'mint-gently', topic:'technique', question:'How should you muddle mint for a Mojito?', options:['Crush it into a paste','Press it gently to release its aroma','Blend it with the soda'], correct:1, explanation:'Gentle pressure releases mint oils. Pulverizing the leaves can add harsh flavors and unpleasant fragments.'},
    {id:'negroni-vermouth', topic:'ingredients', question:'Which vermouth belongs in a classic Negroni?', options:['Sweet red vermouth','Dry vermouth','No vermouth'], correct:0, explanation:'A classic Negroni combines equal parts gin, Campari and sweet red vermouth.'},
    {id:'cream-of-coconut', topic:'ingredients', question:'Which coconut ingredient is specified in PourMind’s Piña Colada?', options:['Unsweetened coconut milk','Sweetened cream of coconut','Coconut water'], correct:1, explanation:'Sweetened cream of coconut provides sweetness and body. Unsweetened coconut cream and coconut milk are different ingredients.'},
    {id:'black-russian', topic:'ingredients', question:'What are the two ingredients in a Black Russian?', options:['Vodka and cream','Rum and espresso','Vodka and coffee liqueur'], correct:2, explanation:'A Black Russian uses vodka and coffee liqueur. Adding cream creates a White Russian.'},
    {id:'orgeat', topic:'ingredients', question:'What is orgeat, used in a classic Mai Tai?', options:['An almond-based syrup','A dry red wine','An orange bitter'], correct:0, explanation:'Orgeat is a sweet almond-based syrup, often with floral flavoring. It adds sweetness, texture and nutty flavor.'},
    {id:'espresso-crema', topic:'ingredients', question:'What gives an Espresso Martini its coffee flavor and foamy top?', options:['Dry vermouth and soda','Fresh espresso, shaken hard with the other ingredients','Cream of coconut'], correct:1, explanation:'Espresso supplies coffee flavor; vigorous shaking helps form the crema-like foam. The recipe also includes coffee liqueur.'},
    {id:'rickey-unsweetened', topic:'ingredients', question:'Which ingredient is absent from PourMind’s classic Gin Rickey?', options:['Gin','Fresh lime juice','Simple syrup'], correct:2, explanation:'A classic Gin Rickey is gin, lime and soda water. It is an unsweetened highball.'},
    {id:'sour-structure', topic:'families', question:'What is the basic structure of a sour cocktail?', options:['Spirit, citrus and a sweetener','Spirit, cream and soda','Only spirit and bitters'], correct:0, explanation:'A sour balances a spirit with citrus acidity and a sweetener. Daiquiris and Whiskey Sours follow this structure.'},
    {id:'boulevardier', topic:'families', question:'What change turns a Negroni-style recipe into a Boulevardier?', options:['Replace sweet vermouth with soda','Use whiskey in place of gin','Remove the Campari'], correct:1, explanation:'A Boulevardier uses whiskey, Campari and sweet vermouth. Ratios may vary, but whiskey is the defining base.'},
    {id:'collins-family', topic:'families', question:'What turns a gin sour into a Collins-style long drink?', options:['Coffee liqueur','Cream','Soda water and a tall, ice-filled serving'], correct:2, explanation:'A Collins combines spirit, lemon and sweetener with soda water, served tall over ice.'},
    {id:'gibson-garnish', topic:'families', question:'Which garnish distinguishes a Gibson from a typical Martini?', options:['A pickled cocktail onion','A pineapple wedge','A mint bouquet'], correct:0, explanation:'The pickled cocktail onion is the Gibson’s characteristic garnish. Its base can be gin or vodka.'},
    {id:'tommys-margarita', topic:'families', question:'How does Tommy’s Margarita differ from an orange-liqueur Margarita?', options:['It replaces tequila with vodka','It uses agave syrup instead of orange liqueur','It adds cranberry juice'], correct:1, explanation:'Tommy’s Margarita combines tequila, lime and agave syrup, with no orange liqueur.'},
    {id:'new-york-sour', topic:'families', question:'What distinguishes a New York Sour from a Whiskey Sour?', options:['A soda-water top','A coffee-bean garnish','A red-wine float'], correct:2, explanation:'A New York Sour finishes a whiskey sour with a red-wine float. Pour the wine gently so it stays on top.'},
    {id:'serve-up', topic:'serving', question:'What does serving a cocktail up usually mean?', options:['Serving it warm','Chilling it with ice, then straining it into a glass without ice','Filling a tall glass with crushed ice'], correct:1, explanation:'An up cocktail is chilled during mixing, then strained into a stemmed glass without serving ice. It differs from neat, which is poured without ice or chilling.'},
    {id:'julep-ice', topic:'serving', question:'Which ice is characteristic of a Mint Julep?', options:['Crushed ice','No ice','One small cube only'], correct:0, explanation:'Crushed ice chills the julep cup, dilutes the drink and supports the aromatic mint bouquet.'},
    {id:'chill-glass', topic:'serving', question:'Why chill the coupe before pouring a Daiquiri?', options:['To make the drink sweeter','To replace shaking','To help the drink stay cold after straining'], correct:2, explanation:'A chilled glass helps an up cocktail retain its serving temperature. It still needs proper chilling and dilution during mixing.'},
    {id:'pornstar-sidecar', topic:'serving', question:'How is the sparkling wine served with PourMind’s Pornstar Martini?', options:['Shaken with the passion fruit','In a separate small glass','Frozen into the garnish'], correct:1, explanation:'Serve the chilled sparkling wine separately as a sidecar. The passion-fruit cocktail is shaken without the wine.'},
    {id:'half-salt-rim', topic:'serving', question:'Why might you salt only half a Margarita glass’s rim?', options:['To offer a choice of salted and unsalted sips','To add carbonation','To chill the tequila'], correct:0, explanation:'A half rim lets the drinker choose a salted or unsalted sip. Keep loose salt outside the glass so it does not fall into the drink.'},
    {id:'jigger', topic:'balance', question:'Why use a jigger when learning a recipe?', options:['It keeps every ingredient warm','It replaces the need for ice','It makes ingredient ratios consistent'], correct:2, explanation:'Measuring gives you a repeatable starting point. You can adjust intentionally after learning how the recipe balances.'},
    {id:'dilution', topic:'balance', question:'What does melting ice contribute while stirring or shaking?', options:['Only decoration','Water that balances strength and texture','Extra alcohol'], correct:1, explanation:'Dilution is part of the recipe: melted ice softens the alcohol’s intensity and helps the flavors come together.'},
    {id:'simple-syrup-ratio', topic:'balance', question:'What does a 1:1 simple syrup ratio describe?', options:['Equal sugar and water, using the recipe’s stated measuring basis','One part syrup to one part spirit','Equal lemon juice and sugar'], correct:0, explanation:'A 1:1 syrup uses equal sugar and water. Follow the stated weight or volume basis consistently; 2:1 rich syrup is sweeter per measure.'},
    {id:'vermouth-storage', topic:'balance', question:'How should you store opened vermouth?', options:['Uncovered beside the stove','In direct sunlight','Sealed in the refrigerator'], correct:2, explanation:'Vermouth is wine-based. Refrigerate it after opening and use it promptly; oxidation gradually changes its flavor.'},
    {id:'fresh-citrus', topic:'balance', question:'What is a useful starting habit when making citrus cocktails?', options:['Replace every juice with soda','Use freshly squeezed juice and measure it','Add citrus only as garnish'], correct:1, explanation:'Freshly squeezed, measured citrus gives a consistent starting point. Fruit acidity varies, so taste and adjust the chosen recipe thoughtfully.'},
    {id:'balance-adjustment', topic:'balance', question:'A measured sour tastes too tart. What is a sensible next adjustment?', options:['Add a little sweetener, then taste again','Double all the alcohol immediately','Remove all the ice and stop measuring'], correct:0, explanation:'Make small, measured adjustments and taste again. Recording the change helps you repeat the balance you prefer.'}
  ]
};
