const variations={
"Whiskey":["Bourbon Old Fashioned","Rye Old Fashioned","Wisconsin Old Fashioned","Oaxacan Old Fashioned","Black Manhattan","New York Sour"],
"Gin":["Dirty Martini","50/50 Martini","Vesper","White Negroni","Gibson","Gin Rickey"],
"Rum":["Coconut Daiquiri","Frozen Daiquiri","Royal Bermuda Yacht Club","Navy Grog","Corn 'n' Oil","Queen's Park Swizzle"],
"Tequila":["Mezcal Margarita","Spicy Margarita","Cadillac Margarita","Skinny Margarita","Ranch Water","Oaxacan Margarita"],
"Vodka":["Dirty Martini","Gibson with Vodka","Pornstar Martini","French Martini","Caipiroska","Vodka Collins"],
"Brandy":["Between the Sheets","Brandy Crusta","Metropolitan","Vieux Carré","Stinger","Japanese Cocktail"]
};

function detailedMethod(d){
 const n=d[0], ing=d[2], original=d[4]||'';
 const exact={
 'Old Fashioned':['Add the sugar and bitters to an Old Fashioned glass; if using a sugar cube, add 1 tsp water and muddle until mostly dissolved.','Add the bourbon or rye and a large ice cube.','Stir in the serving glass for 20–30 seconds, until chilled and lightly diluted.','Express an orange peel over the surface, rub it around the rim, and place it in the drink.'],
 'Whiskey Sour':['Add 2 oz whiskey, 0.75 oz fresh lemon juice, 0.75 oz simple syrup, and optional 0.5 oz egg white to a shaker with no ice.','If using egg white, dry-shake vigorously for 10–15 seconds to build foam.','Fill the shaker with ice and shake hard for another 10–12 seconds.','Double-strain into a chilled coupe, or strain over fresh ice in a rocks glass.','If using egg white, finish with 2–3 drops of Angostura bitters on the foam; garnish with lemon and/or a cherry.'],
 'Manhattan':['Chill a coupe or Nick & Nora glass.','Add rye, sweet vermouth, and 2 dashes Angostura bitters to a mixing glass.','Fill with ice and stir smoothly for 25–30 seconds.','Strain into the chilled glass without ice.','Garnish with a brandied cherry; express an orange peel first if desired.'],
 'Boulevardier':['Add bourbon, Campari, and sweet vermouth to an ice-filled mixing glass.','Stir for 25–30 seconds until thoroughly chilled and properly diluted.','Strain over one large cube in a rocks glass, or serve up in a chilled coupe.','Express an orange peel over the drink and use it as the garnish.'],
 'Mint Julep':['Place 8–10 mint leaves and the simple syrup in a chilled julep cup.','Gently press the mint 2–3 times; do not pulverize it.','Add bourbon, then fill the cup halfway with crushed ice and churn with a bar spoon.','Pack the cup completely with crushed ice to form a mound.','Slap a mint bouquet to release aroma and place it beside the straw.'],
 'Sazerac':['Chill an Old Fashioned glass, then rinse the inside with absinthe and discard the excess.','In a mixing glass, dissolve the sugar with Peychaud’s bitters and a few drops of water.','Add rye whiskey and ice; stir 25–30 seconds.','Strain into the prepared glass with no ice.','Express a lemon peel over the surface and rim; traditionally discard it or place it at the edge.'],
 'Gold Rush':['Add bourbon, fresh lemon juice, and honey syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Strain over a large fresh cube in a rocks glass.','Garnish with a lemon peel or lemon wheel.'],
 'Paper Plane':['Add equal parts bourbon, Aperol, Amaro Nonino, and fresh lemon juice to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe or Nick & Nora glass.','Serve without ice; a lemon twist is optional.'],
 'New York Sour':['Add whiskey, fresh lemon juice, and simple syrup to a shaker; add egg white if using.','Dry-shake first if using egg white, then add ice and shake hard for 10–12 seconds.','Strain over fresh ice in a rocks glass.','Slowly pour the red wine over the back of a bar spoon so it floats as a distinct top layer.','Do not stir after the wine float; garnish with lemon if desired.'],
 'Penicillin':['Add blended Scotch, fresh lemon juice, and honey-ginger syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Strain over one large cube in a rocks glass.','Float smoky Islay Scotch gently over the top using the back of a bar spoon.','Garnish with candied ginger or a lemon peel.'],
 'Dry Martini':['Chill a martini, coupe, or Nick & Nora glass.','Add gin and dry vermouth to a mixing glass filled with ice; add orange bitters if your house spec uses them.','Stir for 25–35 seconds until very cold and silky.','Strain into the chilled glass with no ice.','Express a lemon twist over the surface and discard or garnish; use an olive instead if preferred.'],
 'Negroni':['Add gin, Campari, and sweet vermouth to a mixing glass with ice.','Stir for 20–25 seconds until chilled and diluted.','Strain over one large fresh cube in a rocks glass.','Express an orange peel over the drink and place it in the glass.'],
 'Tom Collins':['Add gin, fresh lemon juice, and simple syrup to a shaker.','Fill with ice and shake for 8–10 seconds.','Strain into an ice-filled Collins glass.','Top with chilled soda water and give one gentle lift with a bar spoon to integrate.','Garnish with a lemon wheel and cherry.'],
 'Gimlet':['Add gin, fresh lime juice, and simple syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe or Nick & Nora glass.','Garnish with a lime wheel or expressed lime peel.'],
 'Gin Fizz':['Add gin, lemon juice, and simple syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Strain into a chilled highball glass without ice.','Top slowly with chilled soda water to create the fizz.','Garnish with a lemon wheel if desired.'],
 'Southside':['Add mint and simple syrup to a shaker and press the mint very gently.','Add gin and fresh lime juice, then fill with ice.','Shake hard for 10–12 seconds.','Double-strain into a chilled coupe to remove mint fragments.','Garnish with a fresh mint leaf.'],
 'Aviation':['Add gin, maraschino liqueur, fresh lemon juice, and crème de violette to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe.','Garnish with a brandied cherry or expressed lemon peel.'],
 'Last Word':['Add equal parts gin, Green Chartreuse, maraschino liqueur, and fresh lime juice to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe or Nick & Nora glass.','Serve without ice; garnish with a cherry only if desired.'],
 "Bee's Knees":['Add gin, fresh lemon juice, and honey syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe.','Express a lemon peel over the surface and garnish with it.'],
 'Clover Club':['Add gin, lemon juice, raspberry syrup, and egg white to a shaker with no ice.','Dry-shake vigorously for 15 seconds to emulsify the egg white.','Add ice and shake hard for another 10–12 seconds.','Double-strain into a chilled coupe.','Allow the foam to settle, then garnish with raspberries or a lemon twist.'],
 'Daiquiri':['Add rum, fresh lime juice, and simple syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe.','Serve immediately with no ice; garnish with a thin lime wheel if desired.'],
 'Mojito':['Place mint, lime juice, and simple syrup in a highball glass; gently press the mint to release aroma without shredding it.','Add rum and fill the glass about three-quarters with crushed ice.','Churn from the bottom with a bar spoon to combine and chill.','Top with soda water, add more crushed ice, and give one final gentle lift.','Garnish with a slapped mint bouquet and lime wedge.'],
 'Mai Tai':['Add aged rum, lime juice, orange curaçao, and orgeat to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Pour or strain over crushed ice in a double rocks glass.','Top with additional crushed ice.','Garnish with a spent lime shell and a large mint bouquet.'],
 "Dark 'n' Stormy":['Fill a highball glass with ice and add chilled ginger beer and lime juice.','Slowly pour the dark rum over the back of a bar spoon so it forms a dark layer on top.','Serve layered for presentation; the guest can stir before drinking.','Garnish with a lime wedge.'],
 'Piña Colada':['Add rum, pineapple juice, coconut cream, and about 1 cup of crushed ice to a blender.','Blend just until smooth and creamy; avoid over-blending into a watery texture.','Pour into a chilled hurricane or large stemmed glass.','Top with a little crushed ice if needed.','Garnish with a pineapple wedge and cherry.'],
 'Jungle Bird':['Add dark rum, Campari, pineapple juice, fresh lime juice, and simple syrup to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Strain over fresh ice in a rocks glass or over crushed ice.','Garnish with a pineapple leaf/wedge and lime.'],
 'Hemingway Daiquiri':['Add white rum, grapefruit juice, lime juice, and maraschino liqueur to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe.','Garnish with a lime wheel or grapefruit peel.'],
 'Painkiller':['Add rum, pineapple juice, orange juice, and coconut cream to a shaker.','Fill with ice and shake very hard to fully emulsify the coconut cream.','Pour over crushed ice in a tall or tiki glass.','Grate fresh nutmeg generously over the top.','Garnish with pineapple and/or an orange wheel.'],
 'Rum Old Fashioned':['Add aged rum, demerara syrup, and bitters to a mixing glass.','Fill with ice and stir for 20–30 seconds.','Strain over one large cube in a rocks glass.','Express an orange peel over the drink and garnish with it.'],
 'El Presidente':['Add rum, dry vermouth, orange curaçao, and grenadine to a mixing glass with ice.','Stir for 25–30 seconds until cold and properly diluted.','Strain into a chilled coupe or Nick & Nora glass.','Express an orange peel and garnish with it.'],
 'Margarita':['Prepare a rocks glass with a half or full salt rim, then fill it with fresh ice if serving on the rocks.','Add tequila, fresh lime juice, and orange liqueur to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain over fresh ice, or strain into a chilled coupe for an up presentation.','Garnish with a lime wheel or wedge.'],
 'Paloma':['Salt the rim of a highball glass if desired and fill with ice.','Add tequila and fresh lime juice.','Top with chilled grapefruit soda, leaving enough room to mix.','Give one gentle stir from the bottom to combine without losing carbonation.','Garnish with a grapefruit or lime wedge.'],
 "Tommy's Margarita":['Prepare a rocks glass with an optional salt rim and fresh ice.','Add tequila, fresh lime juice, and agave nectar to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain over the fresh ice.','Garnish with a lime wheel; do not add orange liqueur—agave is the sweetener in this variation.'],
 'Tequila Sunrise':['Fill a highball glass with ice.','Add tequila and orange juice and stir briefly.','Slowly pour grenadine down the inside of the glass; allow it to sink naturally to create the sunrise gradient.','Do not stir after adding grenadine.','Garnish with an orange slice and cherry.'],
 'El Diablo':['Add tequila, lime juice, and crème de cassis to a shaker.','Fill with ice and shake for 8–10 seconds.','Strain into an ice-filled highball glass.','Top with chilled ginger beer and gently lift once with a bar spoon.','Garnish with a lime wheel.'],
 'Ranch Water':['Fill a tall glass with ice.','Add tequila and freshly squeezed lime juice.','Top generously with very cold sparkling mineral water.','Give one gentle stir to combine while preserving carbonation.','Garnish with a lime wedge.'],
 'Tequila Sour':['Add tequila, fresh citrus, simple syrup, and optional egg white to a shaker without ice.','If using egg white, dry-shake for 10–15 seconds.','Add ice and shake hard for 10–12 seconds.','Double-strain into a chilled coupe or over fresh ice.','Add bitters to the foam if desired and garnish with citrus.'],
 'Mexican Mule':['Fill a copper mug or highball with ice.','Add tequila and fresh lime juice.','Top with chilled ginger beer.','Stir gently once or twice from the bottom.','Garnish with a lime wheel.'],
 'Matador':['Add tequila, pineapple juice, and fresh lime juice to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Strain over fresh ice in a rocks glass or into a chilled coupe, depending on house style.','Garnish with pineapple or lime.'],
 'Cantarito':['If desired, rim a clay cantarito or highball with salt and fill with ice.','Add tequila, fresh grapefruit, orange, and lime juices.','Stir briefly to combine.','Top with chilled grapefruit soda and gently lift once with a spoon.','Garnish with citrus wedges.'],
 'Moscow Mule':['Fill a copper mug or highball with ice.','Add vodka and fresh lime juice.','Top with chilled ginger beer.','Give one gentle stir from the bottom to combine.','Garnish with a lime wheel or wedge.'],
 'Cosmopolitan':['Chill a coupe or martini glass.','Add citrus vodka, cranberry, lime juice, and orange liqueur to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into the chilled glass.','Express an orange peel over the drink and garnish with it.'],
 'Vodka Martini':['Chill a martini or Nick & Nora glass.','Add vodka and dry vermouth to an ice-filled mixing glass.','Stir for 25–35 seconds until very cold and properly diluted.','Strain into the chilled glass.','Garnish with a lemon twist or olive.'],
 'Espresso Martini':['Pull a fresh espresso and allow it to cool briefly so it does not instantly melt the shaker ice.','Add vodka, coffee liqueur, and espresso to a shaker; add simple syrup if your spec calls for it.','Fill completely with ice and shake very hard for 12–15 seconds to aerate the coffee oils.','Double-strain quickly into a chilled coupe or martini glass.','Allow the crema to settle and garnish with three coffee beans.'],
 'White Russian':['Fill a rocks glass with fresh ice.','Add vodka and coffee liqueur and stir briefly.','Slowly pour cream over the back of a spoon for a layered presentation, or add it directly for a mixed drink.','Serve layered or give one gentle stir, depending on preference.'],
 'Black Russian':['Fill a rocks glass with fresh ice.','Add vodka and coffee liqueur directly to the glass.','Stir for 10–15 seconds to chill and combine.','Serve without additional garnish unless desired.'],
 'Bloody Mary':['Add vodka, tomato juice, lemon juice, Worcestershire, hot sauce, salt, and pepper to a mixing tin with ice.','Roll the mixture gently between two tins 4–6 times rather than hard-shaking, which can over-aerate the tomato juice.','Strain or pour over fresh ice in a tall glass.','Taste and adjust seasoning if needed.','Garnish with celery, lemon, olives, or the house garnish.'],
 'Sea Breeze':['Fill a highball glass with ice.','Add vodka and cranberry juice.','Add grapefruit juice and stir gently until evenly combined.','Garnish with a grapefruit or lime wedge.'],
 'Cape Codder':['Fill a highball or rocks glass with ice.','Add vodka and cranberry juice.','Squeeze in a lime wedge and stir gently.','Drop in a fresh lime wedge for garnish.'],
 'Lemon Drop Martini':['Prepare a chilled coupe or martini glass; optionally coat half or all of the rim with fine sugar.','Add citrus vodka, fresh lemon juice, simple syrup, and orange liqueur to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into the prepared glass.','Garnish with a lemon twist.'],
 'Sidecar':['Chill a coupe; optionally prepare a half sugar rim.','Add cognac, orange liqueur, and fresh lemon juice to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain into the chilled glass.','Express an orange or lemon peel over the surface and garnish.'],
 'Brandy Alexander':['Add brandy, crème de cacao, and cream to a shaker.','Fill with ice and shake hard for 12–15 seconds until very cold and lightly aerated.','Double-strain into a chilled coupe.','Grate fresh nutmeg over the surface.'],
 'French 75':['Add gin, fresh lemon juice, and simple syrup to a shaker.','Fill with ice and shake for 8–10 seconds.','Double-strain into a chilled Champagne flute.','Top slowly with chilled Champagne or dry sparkling wine.','Give one very gentle lift if needed and garnish with a long lemon twist.'],
 'Cadillac Margarita':['Prepare a rocks glass with a salt rim and fill it with fresh ice.','Add reposado tequila, fresh lime juice, and orange liqueur to a shaker.','Fill with ice and shake hard for 10–12 seconds.','Double-strain over the fresh ice.','Slowly float 0.5 oz Grand Marnier over the top using the back of a bar spoon so the amber layer remains visible.','Garnish with a lime wheel and serve without stirring the float.'],
 'Pornstar Martini':['Chill a coupe or martini glass.','Add vanilla vodka, passion fruit liqueur, passion fruit purée, lime juice, and vanilla syrup to a shaker.','Fill with ice and shake hard for 12–15 seconds.','Double-strain into the chilled glass.','Garnish with half a passion fruit and serve a small chilled sparkling-wine sidecar separately; do not pour it into the cocktail unless the guest chooses to.'],
 'Caipiroska':['Cut the lime into wedges and place them in a rocks glass with sugar.','Muddle firmly enough to release juice and citrus oils, but avoid pulverizing the bitter white pith.','Add vodka and fill the glass with crushed ice.','Churn thoroughly from the bottom until the sugar is dissolved and the drink is cold.','Crown with more crushed ice and garnish with lime.'],
 "Queen's Park Swizzle":['Add mint leaves, lime juice, demerara syrup, and rum to a tall glass.','Fill about three-quarters with crushed ice.','Place a swizzle stick or bar spoon between your palms and swizzle rapidly until the outside of the glass frosts.','Pack with more crushed ice.','Dash Angostura bitters heavily over the top to create an aromatic bitters layer; garnish with a large mint bouquet.']
 };
 if(exact[n]) return exact[n];
 const lower=(original+' '+ing).toLowerCase();
 let steps=[];
 if(/rim/.test(lower)) steps.push('Prepare the specified glass and rim before mixing so the finished cocktail can be served immediately.');
 if(/muddle/.test(lower)) steps.push('Place the muddled ingredients in the glass or shaker first and press only enough to release juice and aroma without pulverizing bitter pith or herbs.');
 if(/blend/.test(lower)) steps.push('Add the measured ingredients and crushed ice to a blender, then blend only until smooth and uniform.');
 else if(/swizzle/.test(lower)) steps.push('Add the measured ingredients to the serving glass, fill with crushed ice, and swizzle rapidly until the glass becomes thoroughly chilled.');
 else if(/build/.test(lower)||/top with soda|soda water|ginger beer|sparkling/.test(lower)) steps.push('Add the measured non-carbonated ingredients to the serving glass with ice, then add the carbonated ingredient last.');
 else if(/stir/.test(lower)) steps.push('Add all measured ingredients to a mixing glass, fill with ice, and stir smoothly for 25–30 seconds until very cold and properly diluted.');
 else steps.push('Add all measured non-carbonated ingredients to a cocktail shaker.');
 if(!/blend|swizzle|build|stir/.test(lower)) steps.push('Fill the shaker with ice and shake hard for 10–12 seconds, or until the tin is thoroughly chilled.');
 if(/fine-strain|double/.test(lower)) steps.push('Double-strain through both the Hawthorne strainer and a fine mesh strainer into the prepared glass.');
 else if(/strain/.test(lower)) steps.push('Strain into the specified prepared glass, using fresh ice when the recipe is served on the rocks.');
 if(/float/.test(lower)) steps.push('Add the float last, pouring slowly over the back of a bar spoon so it remains as a distinct top layer.');
 if(/top with soda|soda water|ginger beer|sparkling/.test(lower)) steps.push('Top with the chilled carbonated ingredient and stir only once or twice, gently, to preserve carbonation.');
 steps.push('Finish with the listed garnish, placing it neatly so its aroma and presentation complement the first sip.');
 return steps;
}
function methodHTML(d){return '<ol style="padding-left:20px;line-height:1.55">'+detailedMethod(d).map(x=>`<li style="margin:0 0 9px">${x}</li>`).join('')+'</ol>';}

