const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ctx={};vm.runInNewContext(fs.readFileSync(path.join(root,'beer-data.js'),'utf8'),ctx);
const {beers,styles}=ctx.POURMIND_BEERS;
assert.equal(beers.length,232);assert.equal(styles.length,26);assert.equal(new Set(beers.map(b=>b.id)).size,232);assert.equal(new Set(beers.map(b=>b.name.toLowerCase())).size,232);
for(const b of beers){assert.ok(styles.some(s=>s.id===b.style));assert.ok(b.url.startsWith('https://'));assert.ok(b.taste.length>20);assert.ok(/^(?:<)?\d+(?:\.\d+)?$/.test(b.abv));}
for(const style of styles)assert.ok(beers.filter(b=>b.style===style.id).length>=8,style.name);
const beer=name=>beers.find(b=>b.name===name);
assert.equal(beer('Pilsner Urquell').style,'pilsner');assert.equal(beer('Miller Lite').style,'light-lager');assert.equal(beer('New Belgium Fat Tire').style,'blonde');assert.equal(beer('Guinness Draught').style,'stout');assert.equal(beer('Guinness 0').style,'non-alcoholic');assert.equal(beer('Heineken 0.0').abv,'0.0');assert.equal(beer('Athletic Run Wild IPA').abv,'<0.5');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.POURMIND_TEST_URL||'http://127.0.0.1:8000/#beers');await page.locator('.beer-card').first().waitFor();assert.equal(await page.locator('.beer-card').count(),232);assert.match(await page.title(),/Library · Beers/);
 await page.getByRole('searchbox',{name:'Search style, beer, brewery or flavor'}).fill('pilsner');assert.equal(await page.locator('.beer-card').count(),10);assert.ok((await page.locator('.beer-card .demo-label').allTextContents()).every(x=>x==='Pilsner'));await page.locator('.beer-style-summary summary').click();assert.match(await page.locator('.beer-style-summary').innerText(),/Say it simply/i);assert.ok((await page.locator('.beer-card h3').allTextContents()).includes('Pilsner Urquell'));assert.ok(!(await page.locator('.beer-card h3').allTextContents()).includes('Miller Lite'));
 await page.getByRole('button',{name:'Explore Asian brands',exact:true}).click();assert.equal(await page.locator('.beer-card').count(),28);for(const brand of ['Asahi Super Dry','Sapporo Premium Beer','Kirin Ichiban','Tsingtao Premium Lager','Singha Lager','Tiger Beer'])assert.ok((await page.locator('.beer-card h3').allTextContents()).includes(brand));
 await page.getByRole('searchbox').fill('na');assert.equal(await page.locator('.beer-card').count(),10);
 await page.getByRole('searchbox').fill('sierra nevada');assert.equal(await page.locator('.beer-card').count(),5);
 await page.getByRole('searchbox').fill('kolsch');assert.equal(await page.locator('.beer-card').count(),9);
 await page.getByRole('searchbox').fill('');await page.getByLabel('Beer style',{exact:true}).selectOption('non-alcoholic');assert.equal(await page.locator('.beer-card').count(),10);assert.ok((await page.locator('.beer-card .demo-label').allTextContents()).every(x=>x==='Non-alcoholic'));
 await page.getByLabel('Beer style',{exact:true}).selectOption('all');await page.getByRole('searchbox').fill('pilsner');await page.getByRole('button',{name:'Add Pilsner Urquell to our menu',exact:true}).click();await page.locator('[data-beer="menu"][data-id="stocked"]').click();assert.equal(await page.locator('.beer-card').count(),1);await page.reload();await page.locator('[data-beer="menu"][data-id="stocked"]').click();assert.equal(await page.locator('.beer-card').count(),1);
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`page overflow ${width}`);await page.getByRole('button',{name:'Service notes for Pilsner Urquell',exact:true}).click();assert.match(await page.locator('.dialog-body').innerText(),/Tell your guest/);assert.match(await page.locator('.dialog-body').innerText(),/4.4% ABV/);assert.ok(await page.locator('dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1),`dialog overflow ${width}`);await page.locator('[data-beer="detail"][data-id="bitburger-premium-pils"]').click();assert.equal(await page.locator('#dialog-title').innerText(),'Bitburger Premium Pils');await page.keyboard.press('Escape');}
 await page.locator('[data-beer="menu"][data-id="all"]').click();await page.getByRole('searchbox').fill('zzzzzz');assert.equal(await page.locator('.beer-card').count(),0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.locator('.beer-card').count(),232);
 await page.locator('[data-beer="menu"][data-id="stocked"]').click();await page.getByRole('button',{name:'Remove Pilsner Urquell from our menu',exact:true}).click();assert.equal(await page.locator('.beer-card').count(),0);await page.getByRole('button',{name:'Browse all brands',exact:true}).click();assert.equal(await page.locator('.beer-card').count(),232);
 await page.getByRole('searchbox').fill('pilsner');await page.getByRole('button',{name:'Add Pilsner Urquell to our menu',exact:true}).click();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null,null,{timeout:60000});await page.context().setOffline(true);await page.reload();await page.getByRole('searchbox').fill('pilsner');assert.equal(await page.locator('.beer-card').count(),10);await page.locator('[data-beer="menu"][data-id="stocked"]').click();assert.equal(await page.locator('.beer-card').count(),1);assert.deepEqual(errors,[]);
 console.log('PASS: 232 unique beers, minimum eight per category, 28 Asian brands, accurate style examples, pilsner/brand/accent search, NA distinction, local venue menu, detail alternatives, desktop/tablet/mobile fit and offline persistence');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
