const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const context = {};
vm.runInNewContext(fs.readFileSync(path.join(root, 'data.js'), 'utf8'), context);
const {drinks, recipeDetails, photos} = context.POURMIND_DATA;
const recipe = name => {const d=drinks.find(d=>d[0]===name);assert.ok(d,name);return d[2].toLowerCase();};
assert.equal(drinks.length,86);
assert.equal(new Set(drinks.map(d=>d[0])).size,86);
assert.match(recipe('Espresso Martini'),/espresso/);
assert.match(recipe('Espresso Martini'),/coffee liqueur/);
assert.doesNotMatch(recipe('Espresso Martini'),/cream|coconut|pineapple/);
assert.doesNotMatch(recipe('Black Russian'),/cream|milk/);
assert.match(recipe('White Russian'),/cream/);
assert.doesNotMatch(recipe('Gin Rickey'),/syrup|sugar/);
assert.match(recipe('Pornstar Martini'),/passion fruit purée/);
assert.match(recipeDetails['Pornstar Martini'].steps.join(' '),/separate.*do not put it in the shaker/);
assert.match(recipeDetails['French 75'].steps[2],/Top.*Champagne/);
assert.match(recipe('Piña Colada'),/sweetened cream of coconut/);
assert.match(recipe('Matador'),/pineapple/);
assert.match(recipe('Stinger'),/white crème de menthe/);
assert.equal(drinks.find(d=>d[0]==='Wisconsin Old Fashioned')[1],'Brandy');
assert.equal(drinks.find(d=>d[0]==='Oaxacan Old Fashioned')[1],'Tequila');
assert.ok(recipeDetails.Vesper.spirits.includes('Vodka'));
assert.ok(recipeDetails['Vieux Carré'].spirits.includes('Whiskey'));
for(const ingredient of ['gin','campari','sweet vermouth']) assert.match(recipe('Negroni'),new RegExp('1 oz '+ingredient));
const offline = new Set(JSON.parse(fs.readFileSync(path.join(root,'photo-files.json'),'utf8')));
for(const drink of drinks){assert.ok(fs.existsSync(path.join(root,photos[drink[0]])));assert.ok(offline.has(photos[drink[0]]));assert.ok(recipeDetails[drink[0]].steps.length>=3);}
console.log('PASS: 86 recipes; corrected coffee, cream, citrus, carbonated ingredients, spirit categories and complete offline photo coverage');
