const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const p=await browser.newPage({viewport:{width:390,height:844}}),requests=[],errors=[];
 p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});p.on('pageerror',e=>errors.push(e.message));
 const file=process.env.POURMIND_STANDALONE_FILE||path.resolve(__dirname,'../../mobile-build/PourMind-Mobile.html');await p.setContent(fs.readFileSync(file,'utf8'));
 await p.locator('.mobile-nav [data-view="bar"]').click();await p.locator('#main [data-view="reference"]').click();await p.getByLabel('Search wines and spirits',{exact:true}).fill('resling');await p.getByRole('button',{name:'Explore Riesling',exact:true}).click();await p.getByRole('button',{name:'Add Riesling to My bar',exact:true}).click();assert.match(await p.locator('#toast').innerText(),/for this visit/);await p.getByRole('button',{name:'Close dialog',exact:true}).click();await p.locator('#main [data-view="bar"]').click();assert.match(await p.locator('#inventory-list').innerText(),/Riesling/);
 await p.locator('.mobile-nav [data-view="learn"]').click();await p.locator('#main [data-view="families"]').click();await p.getByRole('button',{name:'Explore Daiquiri variations',exact:true}).click();await p.locator('.family-recipe[data-id="Daiquiri"]').click();assert.equal(await p.locator('#dialog-title').innerText(),'Daiquiri');assert.ok(await p.locator('.dialog-photo').evaluate(async img=>{await img.decode();return img.naturalWidth>0;}));await p.getByRole('button',{name:'Close dialog',exact:true}).click();await p.locator('#main [data-view="pairings"]').click();await p.getByLabel('What are you serving?',{exact:true}).selectOption('dessert');assert.match(await p.locator('#pairing-results').innerText(),/sweet/i);
 await p.locator('[data-discovery="pairing-kind"][data-id="cocktail"]').click();await p.locator('#main [data-view="reference"]').click();await p.getByRole('button',{name:'Explore Riesling',exact:true}).click();await p.locator('#dialog-content [data-discovery="food"]').first().click();assert.equal(await p.locator('[data-discovery="pairing-kind"][data-id="wine"]').getAttribute('aria-pressed'),'true');assert.ok(await p.locator('#pairing-results [data-discovery="wine"]').count()>0);
 assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);console.log('PASS: standalone wine profiles, bar additions, families, real recipe images and food pairings; zero external requests; truthful storage fallback.');
}finally{await browser.close();}})().catch(err=>{console.error(err);process.exit(1)});
