const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{pathToFileURL}=require('node:url'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),zip=path.join(root,'downloads/PourMind-Try-It.zip'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'pourmind-portable-'));
execFileSync('python3',['-c',"import zipfile,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; z.extractall(sys.argv[2])",zip,temp]);
const folder=path.join(temp,'PourMind-Try-It'),html=path.join(folder,'PourMind.html');
assert.ok(fs.readFileSync(path.join(folder,'START_HERE.txt'),'utf8').includes('Double-click PourMind.html'));
assert.ok(fs.existsSync(path.join(folder,'THIRD_PARTY_NOTICES.md'))&&fs.existsSync(path.join(folder,'recipes/bar-assistant-LICENSE.txt')));
assert.equal(fs.readFileSync(html,'utf8'),fs.readFileSync(path.join(process.env.POURMIND_BUILD_DIR || path.resolve(root,'../mobile-build'), 'PourMind-Mobile.html'),'utf8'));
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const context=await browser.newContext({viewport:{width:1366,height:900},acceptDownloads:true});let p=await context.newPage();const requests=[],errors=[];const observe=page=>{page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});page.on('pageerror',e=>errors.push(e.message));};observe(p);await context.setOffline(true);
 let fileMode=true;
 try {await p.goto(pathToFileURL(html).href);} catch(error) {if(!error.message.includes('ERR_BLOCKED_BY_ADMINISTRATOR'))throw error;fileMode=false;console.log('Cloud browser policy blocks file URLs; validating the extracted self-contained document in the inline renderer.');await p.close();p=await context.newPage();observe(p);await p.setContent(fs.readFileSync(html,'utf8'));}
 await p.getByRole('button',{name:'Wine library',exact:true}).click();assert.match(await p.locator('.reference-count').innerText(),/244 wines/);await p.getByLabel('Search wines and spirits',{exact:true}).fill('Riesling');await p.getByRole('button',{name:'Explore Riesling',exact:true}).click();await p.getByRole('button',{name:'Add Riesling to My bar',exact:true}).click();assert.match(await p.locator('#toast').innerText(),/added to My bar|added for this visit/);await p.getByRole('button',{name:'Close dialog',exact:true}).click();
 await p.locator('.desktop-nav [data-view="recipes"]').click();assert.equal(await p.locator('.recipe-card').count(),143);await p.locator('.recipe-open[data-name="Daiquiri"]').click();assert.equal(await p.locator('#dialog-title').innerText(),'Daiquiri');assert.ok(await p.locator('.dialog-photo').evaluate(async img=>{await img.decode();return img.naturalWidth>0;}));await p.locator('#dialog-content [data-action="favorite"]').click();await p.getByRole('button',{name:'Close dialog',exact:true}).click();
 await p.locator('.desktop-nav [data-view="learn"]').click();assert.equal(await p.locator('.stage-card').count(),5);await p.locator('[data-academy="tab"][data-id="lessons"]').click();assert.equal(await p.locator('[data-academy="lesson"]').count(),8);await p.locator('[data-academy="lesson"][data-id="measure"]').click();assert.ok((await p.locator('#dialog-content').innerText()).length>200);await p.getByRole('button',{name:'Close dialog',exact:true}).click();
 await p.locator('.desktop-nav [data-view="community"]').click();await p.getByRole('button',{name:'Try an example',exact:true}).click();const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Download recipe file',exact:true}).click()]);const recipe=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(recipe.format,'pourmind-recipe');await p.getByRole('button',{name:'Close dialog',exact:true}).click();
 if(fileMode)await p.reload();assert.equal(await p.locator('#saved-count').innerText(),'1');await p.locator('.desktop-nav [data-view="bar"]').click();assert.match(await p.locator('#inventory-list').innerText(),/Riesling/);
 assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);console.log(fileMode?'PASS: extracted ZIP opens directly from disk offline, including saved-data persistence.':'PASS: extracted ZIP document runs offline in the inline renderer; local-file launch remains blocked by this cloud browser policy.');console.log('PASS: wines, embedded recipe images, lessons and recipe-file export; no server or external requests.');
}finally{await browser.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(err=>{console.error(err);fs.rmSync(temp,{recursive:true,force:true});process.exit(1)});
