const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),sandbox={};
for(const f of ['discovery-data.js','scanner.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox);
assert.deepEqual(Array.from(sandbox.POURMIND_SCANNER.suggest('KENTUCKY BOURBON WHISKEY\nDRY GIN\nRIESLING\nCHARDONNAY')).sort(),['Bourbon','Gin','Riesling','Chardonnay'].sort());
assert.ok(!Array.from(sandbox.POURMIND_SCANNER.suggest('GINGER BEER ORIGIN ORIGINAL')).includes('Gin'));
assert.deepEqual(Array.from(sandbox.POURMIND_SCANNER.suggest('Nothing readable here')),[]);
const base=process.env.POURMIND_TEST_URL||'http://127.0.0.1:8012/';
(async()=>{const options={executablePath:'/usr/bin/chromium',args:['--no-sandbox']};if(base.startsWith('https:')&&process.env.HTTPS_PROXY){const u=new URL(process.env.HTTPS_PROXY);options.proxy={server:`${u.protocol}//${u.hostname}${u.port?':'+u.port:''}`};if(u.username)options.proxy.username=decodeURIComponent(u.username);if(u.password)options.proxy.password=decodeURIComponent(u.password);}const browser=await chromium.launch(options);try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await context.newPage(),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));context.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 await p.goto(base);await p.waitForFunction(()=>navigator.serviceWorker.controller!==null,null,{timeout:90000});await p.getByText('Ready for offline use',{exact:true}).waitFor();
 const go=async view=>p.locator(`.mobile-nav [data-view="${view}"]`).tap();
 await go('recipes');assert.equal(await p.locator('.mobile-nav [data-view="recipes"]').innerText(),'Library');assert.equal(await p.locator('.recipe-card').count(),86);await p.locator('#main [data-view="wines"]').tap();assert.match(await p.locator('.reference-count').innerText(),/244 wines/);assert.equal(await p.locator('.mobile-nav [data-view="recipes"]').getAttribute('aria-current'),'page');await p.locator('#main [data-view="spirits"]').tap();assert.equal(await p.locator('.reference-card').count(),6);
 await go('bar');assert.equal(await p.locator('.inventory-item').count(),0);assert.equal(await p.locator('#main [data-view="wines"],#main [data-view="reference"],#main [data-action="sample-bar"]').count(),0);assert.ok(!/Explore wines|Scan demo|sample ingredients/i.test(await p.locator('#main').innerText()));
 await p.getByLabel('Ingredient name',{exact:true}).fill('Bourbon');await p.locator('#ingredient-form button').tap();
 await context.setOffline(true);await p.getByRole('button',{name:'Scan My Bar',exact:true}).tap();assert.equal(await p.locator('#scan-camera').getAttribute('capture'),'environment');
 await p.locator('#scan-photo').setInputFiles(path.join(root,'tests/fixtures/bar-labels.png'));await p.locator('#scan-confirm').waitFor({timeout:90000});
 const names=await p.locator('.scan-item .input').evaluateAll(items=>items.map(x=>x.value));for(const name of ['Gin','Bourbon','Riesling','Chardonnay'])assert.ok(names.includes(name),`OCR should read ${name}: ${names.join(', ')}`);
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('pourmind:inventory'))),['Bourbon'],'Reading a photo must not write inventory');
 const index=name=>names.indexOf(name);await p.locator('#scan-check-'+index('Riesling')).uncheck();await p.locator('#scan-name-'+index('Gin')).fill('My London dry gin');await p.getByRole('button',{name:'Add selected to My Bar',exact:true}).tap();
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('pourmind:inventory'))),['Bourbon','My London dry gin','Chardonnay']);assert.match(await p.locator('#toast').innerText(),/2 items added/);
 await p.reload();await go('bar');assert.equal(await p.locator('.inventory-item').count(),3);
 await p.getByRole('button',{name:'Scan My Bar',exact:true}).tap();await p.locator('#scan-photo').setInputFiles({name:'invalid.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>')});await p.getByText('Choose a JPG, PNG or WebP photo.',{exact:true}).waitFor();assert.equal(await p.locator('#scan-confirm').count(),0);await p.getByRole('button',{name:'Close dialog',exact:true}).tap();
 await p.getByRole('button',{name:'Scan My Bar',exact:true}).tap();await p.locator('#scan-photo').setInputFiles(path.join(root,'tests/fixtures/bar-labels.png'));await p.getByRole('button',{name:'Close dialog',exact:true}).tap();await p.waitForTimeout(1500);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('pourmind:inventory'))),['Bourbon','My London dry gin','Chardonnay']);
 for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.getByRole('button',{name:'Scan My Bar',exact:true}).click();assert.ok(await p.locator('#dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await p.getByRole('button',{name:'Close dialog',exact:true}).click();}
 assert.ok(requests.every(r=>!/^https?:/.test(r.url)||r.url.startsWith(base)));assert.ok(requests.every(r=>r.method==='GET'),'No photo upload requests');assert.deepEqual(errors,[]);
 console.log('PASS: unified Library; inventory-only My Bar; real on-device OCR works offline; review edits, exclusions, duplicate prevention, cancellation, invalid photos, persistence and responsive layouts; no photo uploads.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
