const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),oldCommit='0cad1b0c14c4691d6f44490db9a9dafbda66e9ef';
const oldFiles=new Map(['index.html','data.js','app.js','mobile.js','styles.css','sw.js'].map(f=>[f,execFileSync('git',['show',`${oldCommit}:${f}`],{cwd:root,maxBuffer:5*1024*1024})]));
let current=false,online=true;
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const file=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1)||'index.html';if(file.includes('..')){res.writeHead(400);return res.end();}if(file==='release.json'&&!online){res.writeHead(503);return res.end();}const content=!current&&oldFiles.get(file);const full=path.join(root,file);if(!content&&!fs.existsSync(full)){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':(file.endsWith('.css') || file.endsWith('.js') && file!=='sw.js')?'public, max-age=3600':'no-store'});res.end(content||fs.readFileSync(full));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 for(const automatic of [false,true]){current=false;online=true;const ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>navigator.serviceWorker.controller!==null,null,{timeout:60000});assert.equal(await p.evaluate(()=>POURMIND_DATA.drinks.length),86);await p.evaluate(()=>{localStorage.setItem('pourmind:saved',JSON.stringify(['Daiquiri']));localStorage.setItem('pourmind:inventory',JSON.stringify(['Gin']));localStorage.setItem('pourmind:learned-questions',JSON.stringify(['stir-old-fashioned']));localStorage.setItem('pourmind:recipe-collection-v1',JSON.stringify([{id:'kept-draft',title:'My draft'}]));});const saved=await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])));
 current=true;if(automatic){await p.reload();}else{online=false;await p.goto(base+'wines.html?open=library&update=2.5.1');await p.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.ok((await p.evaluate(()=>caches.keys())).includes('pourmind-mobile-v7'));online=true;await p.getByRole('button',{name:'Try again',exact:true}).click();}
 await p.waitForURL(/#library$/);await p.waitForFunction(()=>globalThis.POURMIND_DATA?.release==='2.5.1');assert.equal(await p.locator('.recipe-card').count(),143);assert.equal(await p.locator('.generated-cocktail-photo').count(),105);assert.deepEqual(await p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)]))),saved);await p.getByRole('searchbox',{name:'Search recipes'}).fill('Chartreuse Swizzle');await p.getByRole('button',{name:'View Chartreuse Swizzle recipe',exact:true}).click();await p.locator('.dialog-photo').evaluate(i=>i.decode());assert.match(await p.locator('.dialog-photo').getAttribute('src'),/original-iba-chartreuse-swizzle/);assert.deepEqual(errors,[]);await ctx.close();console.log('PASS:',automatic?'ordinary refresh automatically repairs stale scripts':'patch-version recovery repairs stale catalogue; failed online check preserves offline cache');}
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);server.close();process.exit(1)});
