"""Compile the named recipe/photo catalogue; reject incomplete or mismatched entries."""
import hashlib
import json
import re
import unicodedata
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def build():
    mapping = json.loads((ROOT / 'recipes/photo-map.json').read_text())
    drinks, details, photos = [], {}, {}
    normalized_names = set()
    for number, line in enumerate((ROOT / 'recipes/catalogue.txt').read_text().splitlines(), 1):
        if not line.strip() or line.startswith('#'):
            continue
        fields = line.split('|')
        if len(fields) != 8 or not all(fields):
            raise ValueError(f'Incomplete recipe on line {number}')
        name, spirit, family, glass, garnish, ingredients, steps, note = fields
        normalized = re.sub(r'[^a-z0-9]', '', unicodedata.normalize('NFKD', name).encode('ascii', 'ignore').decode().lower())
        if normalized in normalized_names or name not in mapping:
            raise ValueError(f'Duplicate recipe or missing photo: {name}')
        normalized_names.add(normalized)
        image = mapping[name]
        asset = ROOT / image['file']
        if not asset.is_file() or hashlib.sha256(asset.read_bytes()).hexdigest() != image['imageSha256']:
            raise ValueError(f'Missing or changed image: {name}')
        ingredient_list, method = ingredients.split('~'), steps.split('~')
        if len(method) < 3 or any(not item[0].isdigit() and not item.startswith('A few drops ') for item in ingredient_list):
            raise ValueError(f'Missing quantities or method: {name}')
        spirits = [spirit]
        extra = {'Vesper': ['Vodka'], 'Vieux Carré': ['Whiskey'], 'Between the Sheets': ['Rum'], 'Angel Face': ['Brandy'], 'Illegal': ['Rum'], 'Long Island Iced Tea': ['Tequila', 'Rum', 'Gin'], 'Suffering Bastard': ['Gin'], 'Trinidad Sour': ['Whiskey'], 'Pisco Punch': ['Wine'], 'Porto Flip': ['Wine'], 'Champagne Cocktail': ['Brandy']}
        if name in extra:
            spirits.extend(extra[name])
        details[name] = dict(family=family, steps=method, note=note, spirits=spirits,
                             imageKind=image['kind'], imageCredit=image['credit'], reference=image['reference'])
        photos[name] = image['file']
        drinks.append([name, spirit, ' • '.join(ingredient_list), name, '', glass, garnish])
    if not drinks or set(details) != set(mapping):
        raise ValueError('Catalogue must contain matching named photo/recipe pairs')
    coverage = json.loads((ROOT / 'recipes/iba-coverage.json').read_text())
    for entry in coverage['cocktails']:
        if entry['recipeName'] not in details:
            raise ValueError(f"Missing IBA recipe: {entry['ibaName']}")
        if entry['ibaName'] != entry['recipeName']:
            details[entry['recipeName']].setdefault('aliases', []).append(entry['ibaName'])
    release = json.loads((ROOT / 'release.json').read_text())['version']
    payload = dict(release=release, drinks=drinks, photos=photos, recipeDetails=details)
    (ROOT / 'data.js').write_text('// Generated by tools/build_catalogue.py; edit recipes/ instead.\n'
                                + 'globalThis.POURMIND_DATA = '
                                + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n')
    # Version asset URLs so recovery also bypasses the browser HTTP cache.
    shell = ROOT / 'index.html'
    markup = shell.read_text()
    markup = re.sub(r'(src|href)="([^"?]+\.(?:js|css))(?:\?[^" ]*)?"',
                    lambda m: f'{m[1]}="{m[2]}?v={release}"', markup)
    shell.write_text(markup)
    (ROOT / 'photo-files.json').write_text(json.dumps(sorted(set(photos.values())), indent=2) + '\n')
    print(f'Built {len(drinks)} complete recipes with {len(set(photos.values()))} image assets')
if __name__ == '__main__':
    build()
