"""Compile the named recipe/photo catalogue; reject incomplete or mismatched entries."""
import hashlib
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def build():
    mapping = json.loads((ROOT / 'recipes/photo-map.json').read_text())
    drinks, details, photos = [], {}, {}
    for number, line in enumerate((ROOT / 'recipes/catalogue.txt').read_text().splitlines(), 1):
        if not line.strip() or line.startswith('#'):
            continue
        fields = line.split('|')
        if len(fields) != 8 or not all(fields):
            raise ValueError(f'Incomplete recipe on line {number}')
        name, spirit, family, glass, garnish, ingredients, steps, note = fields
        if name in details or name not in mapping:
            raise ValueError(f'Duplicate recipe or missing photo: {name}')
        image = mapping[name]
        asset = ROOT / image['file']
        if not asset.is_file() or hashlib.sha256(asset.read_bytes()).hexdigest() != image['imageSha256']:
            raise ValueError(f'Missing or changed image: {name}')
        ingredient_list, method = ingredients.split('~'), steps.split('~')
        if len(method) < 3 or any(not item[0].isdigit() for item in ingredient_list):
            raise ValueError(f'Missing quantities or method: {name}')
        spirits = [spirit]
        extra = {'Vesper': 'Vodka', 'Vieux Carré': 'Whiskey', 'Between the Sheets': 'Rum'}
        if name in extra:
            spirits.append(extra[name])
        details[name] = dict(family=family, steps=method, note=note, spirits=spirits,
                             imageKind=image['kind'], imageCredit=image['credit'], reference=image['reference'])
        photos[name] = image['file']
        drinks.append([name, spirit, ' • '.join(ingredient_list), name, '', glass, garnish])
    if len(drinks) != 86 or set(details) != set(mapping):
        raise ValueError('Catalogue must contain exactly the 86 named photo/recipe pairs')
    payload = dict(drinks=drinks, photos=photos, recipeDetails=details)
    (ROOT / 'data.js').write_text('// Generated by tools/build_catalogue.py; edit recipes/ instead.\n'
                                + 'globalThis.POURMIND_DATA = '
                                + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n')
    (ROOT / 'photo-files.json').write_text(json.dumps(sorted(set(photos.values())), indent=2) + '\n')
    print(f'Built {len(drinks)} complete recipes with {len(set(photos.values()))} image assets')
if __name__ == '__main__':
    build()
