"""Validate and compile the US beer brand/style reference."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'beers/catalogue.json').read_text())
styles={s['id']:s for s in data['styles']}
if len(styles)!=len(data['styles']):raise ValueError('Duplicate beer style')
ids,names=set(),set()
for b in data['beers']:
 if b['id'] in ids or b['name'].casefold() in names:raise ValueError('Duplicate beer: '+b['name'])
 ids.add(b['id']);names.add(b['name'].casefold())
 if b['style'] not in styles:raise ValueError('Unknown style: '+b['name'])
 if not re.fullmatch(r'(?:<)?\d+(?:\.\d+)?',b['abv']):raise ValueError('Invalid ABV: '+b['name'])
 if not b['url'].startswith('https://') or not all(b[k] for k in ['name','brewer','origin','taste']):raise ValueError('Incomplete beer: '+b['name'])
for s in styles.values():
 if not all(s[k] for k in ['name','taste','say','body','bitterness','serve','pairing']):raise ValueError('Incomplete style: '+s['id'])
 if not any(b['style']==s['id'] for b in data['beers']):raise ValueError('Empty style: '+s['id'])
(ROOT/'beer-data.js').write_text('// Generated by tools/build_beers.py; edit beers/catalogue.json instead.\nglobalThis.POURMIND_BEERS = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
print(f"Built {len(data['beers'])} beer products across {len(styles)} styles")
